apps/accounts/urls.py
from django.urls import path
from .views import login_user, register, candidate

app_name = 'accounts'

urlpatterns = [
    path('login/', login_user, name='login'),
    path('register/', register, name='sign-up'),
    path('candidate/', candidate, name='candidate'),
]

apps/home/urls.py
from django.urls import path
from .views import home

app_name = 'home'

urlpatterns = [
    path('', home, name='index'),
]

apps/jobs/urls.py
from django.urls import path
from .views import jobs, job_detail

app_name = 'jobs'

urlpatterns = [
    path('', jobs, name='job'),
    path('detail/<slug:slug>/', job_detail, name='detail'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.home.urls', namespace='home')),
    path('blogs/', include('apps.blog.urls', namespace='blog')),
    path('contact/', include('apps.contact.urls', namespace='contact')),
    path('jobs/', include('apps.jobs.urls', namespace='jobs')),
    path('accounts/', include('apps.accounts.urls', namespace='accounts')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/home/models.py
from django.db import models

# Create your models here.

apps/home/views.py
from django.shortcuts import render


def home(request):
    ctx = {

    }
    return render(request, 'home/index.html', ctx)

templates/home/index.html
{% extends 'base.html' %}
{% load static %}



{% block content %}

    <main>

        <div class="slider-area position-relative ">

            <div class="single-sliders slider-height  gray-bg d-flex align-items-center">
                <div class="container">
                    <div class="row align-items-center">
                        <div class="col-xl-6 col-lg-7">
                            <div class="hero-caption">
                                <span>Easiest way to find a perfect job</span>
                                <h1>Find Your Next Dream Job</h1>

                                <div class="slider-btns">
                                    <a href="{% url 'jobs:job' %}" class="btn hero-btn">Looking For a Job?</a>
                                    <a href="{% url 'accounts:candidate' %}" class="hero-btn2">Find Talent</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="hero-tittle">
                <h2>jobs</h2>
            </div>

            <div class="hero-img">
                <img src="{% static 'assets/img/hero/hero-img.png' %}" alt="">
            </div>

            <div class="hero-shape bounce-animate">
                <img src="{% static 'assets/img/hero/hero-shape.png' %}" alt="">
            </div>

            <div class="hero-shape2">
                <img src="{% static 'assets/img/hero/hero-shape2.png' %}" alt="">
            </div>
        </div>


        <section class="top-jobs fix ">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-xl-8 col-lg-9 col-md-12">

                        <div class="section-tittle section-tittle3 text-center mb-10">
                            <span>1000+</span>
                            <h2>Browse From Our Top Jobs</h2>
                            <p>The automated process starts as soon as your clothes go into the machine. The outcome is
                                gleaming clothes. Placeholder text commonly used.</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="container-fluid p-0">
                <div class="top-job-slider ">

                    <div class="single-top-jobs ">
                        <div class="services-ion">
                            <img src="{% static 'assets/img/icon/job-iocn1.svg' %}" alt="">
                        </div>
                        <div class="services-cap">
                            <h5><a href="#">Design & creatives</a></h5>
                            <p>The automated process starts as soon as your clothes go into.</p>
                            <a href="#" class="product_btn">Apply Now</a>
                        </div>
                    </div>

                    <div class="single-top-jobs ">
                        <div class="services-ion">
                            <img src="{% static 'assets/img/icon/job-iocn2.svg' %}" alt="">
                        </div>
                        <div class="services-cap">
                            <h5><a href="#">Design & creatives</a></h5>
                            <p>The automated process starts as soon as your clothes go into.</p>
                            <a href="#" class="product_btn">Apply Now</a>
                        </div>
                        <div class="stickers">
                            <span>Remote</span>
                        </div>
                    </div>

                    <div class="single-top-jobs ">
                        <div class="services-ion">
                            <img src="{% static 'assets/img/icon/job-iocn3.svg' %}" alt="">
                        </div>
                        <div class="services-cap">
                            <h5><a href="#">Design & creatives</a></h5>
                            <p>The automated process starts as soon as your clothes go into.</p>
                            <a href="#" class="product_btn">Apply Now</a>
                        </div>
                        <div class="stickers">
                            <span>Remote</span>
                        </div>
                    </div>

                    <div class="single-top-jobs ">
                        <div class="services-ion">
                            <img src="{% static 'assets/img/icon/job-iocn4.svg' %}" alt="">
                        </div>
                        <div class="services-cap">
                            <h5><a href="#">Design & creatives</a></h5>
                            <p>The automated process starts as soon as your clothes go into.</p>
                            <a href="#" class="product_btn">Apply Now</a>
                        </div>
                    </div>

                    <div class="single-top-jobs ">
                        <div class="services-ion">
                            <img src="{% static 'assets/img/icon/job-iocn5.svg' %}" alt="">
                        </div>
                        <div class="services-cap">
                            <h5><a href="#">Design & creatives</a></h5>
                            <p>The automated process starts as soon as your clothes go into.</p>
                            <a href="#" class="product_btn">Apply Now</a>
                        </div>
                    </div>

                    <div class="single-top-jobs ">
                        <div class="services-ion">
                            <img src="{% static 'assets/img/icon/job-iocn2.svg' %}" alt="">
                        </div>
                        <div class="services-cap">
                            <h5><a href="#">Design & creatives</a></h5>
                            <p>The automated process starts as soon as your clothes go into.</p>
                            <a href="#" class="product_btn">Apply Now</a>
                        </div>
                        <div class="stickers">
                            <span>Remote</span>
                        </div>
                    </div>
                </div>
            </div>
        </section>


        <section class="about-area gray-bg section-padding2">
            <div class="container">
                <div class="row align-items-center justify-content-between">
                    <div class="col-xl-6 col-lg-7 col-md-10">
                        <div class="support-location-img">
                            <img src="{% static 'assets/img/gallery/about.png' %}" alt="">
                        </div>
                    </div>
                    <div class="col-xl-5 col-lg-5 col-md-10">
                        <div class="right-caption">

                            <div class="section-tittle section-tittle3">
                                <h2>We Build Lasting Relationships Between Candidates & Businesses</h2>
                            </div>
                            <div class="support-caption">
                                <p class="pera-top">The automated process starts as soon as your clothes
                                    go into the machine. The outcome is gleaming clothes.
                                    Placeholder text commonly used.</p>
                                <p class="mb-45">Automated process starts as soon as your clothes
                                    go into the machine. The outcome is gleaming clothes.
                                    Placeholder text commonly used.</p>
                                <a href="#" class="btn about-btn">Find Talent</a>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="about-tittle">
                    <h2>Talents</h2>
                </div>
            </div>
        </section>


        <section class="job-category section-padding">
            <div class="container">

                <div class="row justify-content-center mb-55">
                    <div class="col-xl-8">
                        <div class="section-tittle section-tittle3 text-center">
                            <h2>Browse From Top Categories</h2>
                            <p>The automated process starts as soon as your clothes go into the machine. The outcome is
                                gleaming clothes. Placeholder text commonly used.</p>
                        </div>
                    </div>
                </div>
                <div class="row">



                    <div class="col-lg-4 col-md-6 col-sm-6">
                        <div class="single-cat">
                            <div class="cat-icon">
                                <img src="{% static 'assets/img/icon/top-cat5.svg' %}" alt="">
                            </div>
                            <div class="cat-cap">
                                <h5><a href="#">Corporate</a></h5>
                                <p>The automated process starts as soon as your clothes go into.</p>
                                <a href="#" class="view_btn">Browse Job</a>
                            </div>
                        </div>
                    </div>


                </div>
            </div>
        </section>


        <div class="testimonial-area">
            <div class="container">
                <div class="testimonial-wrapper">
                    <div class="row justify-content-center">
                        <div class="col-xl-8 col-lg-10">
                            <div class="h1-testimonial-active dot-style">


                                <div class="single-testimonial position-relative">
                                    <div class="testimonial-caption">
                                        <img src="{% static 'assets/img/icon/quotes-sign.png' %}" alt="" class="quotes-sign">
                                        <p>"The automated process starts as soon as your clothe go into the machine.
                                            This
                                            site outcome is gleaming clothe. Placeholder text commonly used. In
                                            publishing
                                            and graphic.</p>
                                    </div>

                                    <div class="testimonial-founder d-flex align-items-center">
                                        <div class="founder-img">
                                            <img src="{% static 'assets/img/icon/testimonial.png' %}" alt="">
                                        </div>
                                        <div class="founder-text">
                                            <span>Robart Brown</span>
                                            <p>Creative designer at Colorlib</p>
                                        </div>
                                    </div>
                                </div>



                            </div>
                        </div>
                    </div>

                    <div class="t-shape">
                        <img src="{% static 'assets/img/gallery/testimonial-shape.png' %}" alt="">
                    </div>
                </div>
            </div>
        </div>

    </main>

{% endblock %}