apps/blog/urls.py
from django.urls import path
from .views import blog, blog_detail

app_name = 'blog'

urlpatterns = [
    path('', blog, name='blog'),
    path('detail/<int:yaer>/<int:month>/<int:day>/<slug:slug>/', blog_detail, name='detail'),
]

apps/contact/urls.py
from django.urls import path
from .views import contact

app_name = 'contact'

urlpatterns = [
    path('', contact, name='contact'),
]

apps/home/urls.py
from django.urls import path
from .views import home

app_name = 'home'

urlpatterns = [
    path('', home, name='index'),
]

apps/jobs/urls.py
from django.urls import path
from .views import jobs, job_detail

app_name = 'jobs'

urlpatterns = [
    path('', jobs, name='job'),
    path('detail/<slug:slug>/', job_detail, name='detail'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.home.urls', namespace='home')),
    path('blogs/', include('apps.blog.urls', namespace='blog')),
    path('contact/', include('apps.contact.urls', namespace='contact')),
    path('jobs/', include('apps.jobs.urls', namespace='jobs')),
    path('accounts/', include('apps.accounts.urls', namespace='accounts')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}

<!doctype html>
<html class="no-js" lang="zxx">

<!-- Mirrored from preview.colorlib.com/theme/jobsco/ by HTTrack Website Copier/3.x [XR&CO'2014], Mon, 10 Jul 2023 15:00:16 GMT -->
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>JobBoard HTML-5 Template</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="manifest" href="../site.html">
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'assets/img/favicon.ico' %}">

    <link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/slicknav.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/animate.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/fontawesome-all.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/themify-icons.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/slick.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/nice-select.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
    <script nonce="9552bf11-6b0b-485b-b492-228920a348ae">(function (w, d) {
        !function (f, g, h, i) {
            f[h] = f[h] || {};
            f[h].executed = [];
            f.zaraz = {deferred: [], listeners: []};
            f.zaraz.q = [];
            f.zaraz._f = function (j) {
                return function () {
                    var k = Array.prototype.slice.call(arguments);
                    f.zaraz.q.push({m: j, a: k})
                }
            };
            for (const l of ["track", "set", "debug"]) f.zaraz[l] = f.zaraz._f(l);
            f.zaraz.init = () => {
                var m = g.getElementsByTagName(i)[0], n = g.createElement(i), o = g.getElementsByTagName("title")[0];
                o && (f[h].t = g.getElementsByTagName("title")[0].text);
                f[h].x = Math.random();
                f[h].w = f.screen.width;
                f[h].h = f.screen.height;
                f[h].j = f.innerHeight;
                f[h].e = f.innerWidth;
                f[h].l = f.location.href;
                f[h].r = g.referrer;
                f[h].k = f.screen.colorDepth;
                f[h].n = g.characterSet;
                f[h].o = (new Date).getTimezoneOffset();
                if (f.dataLayer) for (const s of Object.entries(Object.entries(dataLayer).reduce(((t, u) => ({...t[1], ...u[1]})), {}))) zaraz.set(s[0], s[1], {scope: "page"});
                f[h].q = [];
                for (; f.zaraz.q.length;) {
                    const v = f.zaraz.q.shift();
                    f[h].q.push(v)
                }
                n.defer = !0;
                for (const w of [localStorage, sessionStorage]) Object.keys(w || {}).filter((y => y.startsWith("_zaraz_"))).forEach((x => {
                    try {
                        f[h]["z_" + x.slice(7)] = JSON.parse(w.getItem(x))
                    } catch {
                        f[h]["z_" + x.slice(7)] = w.getItem(x)
                    }
                }));
                n.referrerPolicy = "origin";
                n.src = "https://preview.colorlib.com/cdn-cgi/zaraz/s.js?z=" + btoa(encodeURIComponent(JSON.stringify(f[h])));
                m.parentNode.insertBefore(n, m)
            };
            ["complete", "interactive"].includes(g.readyState) ? zaraz.init() : f.addEventListener("DOMContentLoaded", zaraz.init)
        }(w, d, "zarazData", "script");
    })(window, document);</script>
</head>
<body>
<header>
    <div class="header-area header-transparent">
        <div class="main-header header-sticky">
            <div class="container">
                <div class="menu-wrapper d-flex align-items-center justify-content-between">
                    <div class="left-content d-flex align-items-center">
                        <div class="logo mr-45">
                            <a href="index-2.html"><img src="{% static 'assets/img/logo/logo.png' %}" alt=""></a>
                        </div>

                        <div class="main-menu d-none d-lg-block">
                            <nav>
                                <ul id="navigation">
                                    <li><a href="{% url 'home:index' %}">Home</a></li>
                                    <li><a href="{% url 'jobs:job' %}">Browse Job</a></li>
                                    <li><a href="#">Page</a>
                                        <ul class="submenu">
                                            <li><a href="{% url 'blog:blog' %}">Blog</a></li>
                                            <li><a href="{% url 'accounts:candidate' %}">Candidates</a></li>
                                        </ul>
                                    </li>
                                    <li><a href="{% url 'contact:contact' %}">Contact</a></li>
                                </ul>
                            </nav>
                        </div>
                    </div>

                    <div class="buttons">
                        <ul>
                            <li class="button-header">
                                <a href="#" class="header-btn mr-10"> <i class="fas fa-phone-alt"></i>Post A Job</a>
                                <a href="{% url 'accounts:login' %}" class="btn header-btn2">Log In</a>
                            </li>
                        </ul>
                    </div>
                </div>

                <div class="col-12">
                    <div class="mobile_menu d-block d-lg-none"></div>
                </div>
            </div>
        </div>
    </div>
</header>


{% block content %}

{% endblock %}

<footer>
    <div class="footer-area footer-padding gray-bg">
        <div class="footer-wrapper ">
            <div class="container">
                <div class="row d-flex justify-content-between">
                    <div class="col-xl-4 col-lg-4 col-md-6 col-sm-6">
                        <div class="single-footer-caption mb-50">
                            <div class="single-footer-caption mb-30">

                                <div class="footer-logo mb-25">
                                    <a href="{% url 'home:index' %}"><img src="{% static 'assets/img/logo/logo2_footer.png' %}" alt=""></a>
                                </div>
                                <div class="footer-tittle">
                                    <div class="footer-pera">
                                        <p>The automated process starts as soon as your clothes go into the machine.The
                                            outcome is gleaming clothes.</p>
                                    </div>
                                </div>
                                <div class="footer-social">
                                    <a href="#"><i class="fab fa-instagram"></i></a>
                                    <a href="https://bit.ly/sai4ull"><i class="fab fa-facebook-f"></i></a>
                                    <a href="#"><i class="fab fa-twitter"></i></a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-2 col-lg-2 col-md-4 col-sm-5">
                        <div class="single-footer-caption mb-50">
                            <div class="footer-tittle">
                                <h4>Useful links</h4>
                                <ul>
                                    <li><a href="#">Design & creatives</a></li>
                                    <li><a href="#">Telecommunication</a></li>
                                    <li><a href="#">Restaurant</a></li>
                                    <li><a href="#">Programing</a></li>
                                    <li><a href="#">Architecture</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-3 col-lg-3 col-md-6 col-sm-6">
                        <div class="single-footer-caption mb-50">
                            <div class="footer-tittle">
                                <h4>Subscribe Newsletter</h4>
                                <p>Subscribe newsletter to get updates about new jobs.</p>
                            </div>

                            <div class="footer-form">
                                <div id="mc_embed_signup">
                                    <form target="_blank"
                                          action="https://spondonit.us12.list-manage.com/subscribe/post?u=1462626880ade1ac87bd9c93a&amp;id=92a4423d01"
                                          method="get" class="subscribe_form relative mail_part" novalidate="true">
                                        <input type="email" name="EMAIL" id="newsletter-form-email"
                                               placeholder="  Enter your email">
                                        <div class="form-icon">
                                            <button type="submit" name="submit" id="newsletter-submit"
                                                    class="email_icon newsletter-submit button-contactForm">
                                                Subscribe
                                            </button>
                                        </div>
                                        <div class="mt-10 info"></div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="footer-bottom-area">
                <div class="container">
                    <div class="footer-border">
                        <div class="row d-flex align-items-center">
                            <div class="col-xl-12 ">
                                <div class="footer-copy-right text-center">
                                    <p>Copyright &copy;<script>document.write(new Date().getFullYear());</script>
                                        All rights reserved | This template is made with <i
                                                class="fa fa-heart color-danger" aria-hidden="true"></i> by <a
                                                href="https://colorlib.com/" target="_blank" rel="nofollow noopener">Colorlib</a>
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>

<div id="back-top">
    <a title="Go to Top" href="#"> <i class="fas fa-level-up-alt"></i></a>
</div>


<script src="{% static 'assets/js/vendor/modernizr-3.5.0.min.js' %}"></script>
<script src="{% static 'assets/js/vendor/jquery-1.12.4.min.js' %}"></script>
<script src="{% static 'assets/js/popper.min.js' %}"></script>
<script src="{% static 'assets/js/bootstrap.min.js' %}"></script>

<script src="{% static 'assets/js/owl.carousel.min.js' %}"></script>
<script src="{% static 'assets/js/slick.min.js' %}"></script>
<script src="{% static 'assets/js/jquery.slicknav.min.js' %}"></script>
<script src="{% static 'assets/js/range.js' %}"></script>

<script src="{% static 'assets/js/wow.min.js' %}"></script>
<script src="{% static 'assets/js/jquery.magnific-popup.js' %}"></script>
<script src="{% static 'assets/js/jquery.nice-select.min.js' %}"></script>

<script src="{% static 'assets/js/contact.js' %}"></script>
<script src="{% static 'assets/js/jquery.form.js' %}"></script>
<script src="{% static 'assets/js/jquery.validate.min.js' %}"></script>
<script src="{% static 'assets/js/mail-script.js' %}"></script>
<script src="{% static 'assets/js/jquery.ajaxchimp.min.js' %}"></script>

<script src="{% static 'assets/js/plugins.js' %}"></script>
<script src="{% static 'assets/js/main.js' %}"></script>

<script async src="https://www.googletagmanager.com/gtag/js?id=UA-23581568-13"></script>
<script>
    window.dataLayer = window.dataLayer || [];

    function gtag() {
        dataLayer.push(arguments);
    }

    gtag('js', new Date());

    gtag('config', 'UA-23581568-13');
</script>
<script defer src="https://static.cloudflareinsights.com/beacon.min.js/v52afc6f149f6479b8c77fa569edb01181681764108816"
        integrity="sha512-jGCTpDpBAYDGNYR5ztKt4BQPGef1P0giN6ZGVUi835kFF88FOmmn8jBQWNgrNd8g/Yu421NdgWhwQoaOPFflDw=="
        data-cf-beacon='{"rayId":"7e49acddeda307a5","version":"2023.4.0","b":1,"token":"cd0b4b3a733644fc843ef0b185f98241","si":100}'
        crossorigin="anonymous"></script>
</body>

<!-- Mirrored from preview.colorlib.com/theme/jobsco/ by HTTrack Website Copier/3.x [XR&CO'2014], Mon, 10 Jul 2023 15:01:17 GMT -->
</html>

templates/sidebar.html
{% load static %}
{% load resent_blogs %}
{% resent_blog as rb %}
{% tags as tags %}
{% categories as categories %}

<div class="col-lg-4">
    <div class="blog_right_sidebar">
        <aside class="single_sidebar_widget search_widget">
            <form action="#">
                <div class="form-group">
                    <div class="input-group mb-3">
                        <input type="text" class="form-control" placeholder='Search Keyword'
                               onfocus="this.placeholder = ''"
                               onblur="this.placeholder = 'Search Keyword'">
                        <div class="input-group-append">
                            <button class="btns" type="button"><i class="ti-search"></i></button>
                        </div>
                    </div>
                </div>
                <button class="button rounded-0 primary-bg text-white w-100 btn_1 boxed-btn"
                        type="submit">Search
                </button>
            </form>
        </aside>
        <aside class="single_sidebar_widget post_category_widget">
            <h4 class="widget_title" style="color: #2d2d2d;">Category</h4>
            <ul class="list cat-list">
                {% for category in categories %}
                    <li>
                        <a href="#" class="d-flex">
                            <p>{{ category.title }}</p>
                            <p>({{ category.blog_set.count }})</p>
                        </a>
                    </li>
                {% endfor %}

            </ul>
        </aside>
        <aside class="single_sidebar_widget popular_post_widget">
            <h3 class="widget_title" style="color: #2d2d2d;">Recent Post</h3>

            {% for r in rb %}
                <div class="media post_item">
                    {% if r.image %}
                        <img src="{{ r.image.url }}" alt="post" style="width: 150px">
                    {% endif %}
                    <div class="media-body">
                        <a href="{% url 'blog:detail' r.slug %}">
                            <h3 style="color: #2d2d2d;">{{ r.title|slice:"40" }}...</h3>
                        </a>
                        <p>{{ r.created_date|date:"F d, Y" }}</p>
                    </div>
                </div>
            {% endfor %}


        </aside>
        <aside class="single_sidebar_widget tag_cloud_widget">
            <h4 class="widget_title" style="color: #2d2d2d;">Tag Clouds</h4>
            <ul class="list">
                {% for tag in tags %}
                    <li>
                        <a href="#">{{ tag.title }}</a>
                    </li>
                {% endfor %}


            </ul>
        </aside>
        <aside class="single_sidebar_widget instagram_feeds">
            <h4 class="widget_title" style="color: #2d2d2d;">Instagram Feeds</h4>
            <ul class="instagram_row flex-wrap">
                <li>
                    <a href="#">
                        <img class="img-fluid" src="{% static 'assets/img/post/post_5.jpg' %}"
                             alt="">
                    </a>
                </li>
                <li>
                    <a href="#">
                        <img class="img-fluid" src="{% static 'assets/img/post/post_6.jpg' %}"
                             alt="">
                    </a>
                </li>
                <li>
                    <a href="#">
                        <img class="img-fluid" src="{% static 'assets/img/post/post_7.jpg' %}"
                             alt="">
                    </a>
                </li>
                <li>
                    <a href="#">
                        <img class="img-fluid" src="{% static 'assets/img/post/post_8.jpg' %}"
                             alt="">
                    </a>
                </li>
                <li>
                    <a href="#">
                        <img class="img-fluid" src="{% static 'assets/img/post/post_9.jpg' %}"
                             alt="">
                    </a>
                </li>
                <li>
                    <a href="#">
                        <img class="img-fluid" src="{% static 'assets/img/post/post_10.jpg' %}"
                             alt="">
                    </a>
                </li>
            </ul>
        </aside>
        <aside class="single_sidebar_widget newsletter_widget">
            <h4 class="widget_title" style="color: #2d2d2d;">Newsletter</h4>
            <form action="#">
                <div class="form-group">
                    <input type="email" class="form-control" onfocus="this.placeholder = ''"
                           onblur="this.placeholder = 'Enter email'" placeholder='Enter email'
                           required>
                </div>
                <button class="button rounded-0 primary-bg text-white w-100 btn_1 boxed-btn"
                        type="submit">Subscribe
                </button>
            </form>
        </aside>
    </div>
</div>

templates/site.html
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html>
<head>
    <title>404 Not Found</title>
    <script nonce="127f933c-8aad-4a0c-b6f9-abe5a5f39588">(function (w, d) {
        !function (f, g, h, i) {
            f[h] = f[h] || {};
            f[h].executed = [];
            f.zaraz = {deferred: [], listeners: []};
            f.zaraz.q = [];
            f.zaraz._f = function (j) {
                return function () {
                    var k = Array.prototype.slice.call(arguments);
                    f.zaraz.q.push({m: j, a: k})
                }
            };
            for (const l of ["track", "set", "debug"]) f.zaraz[l] = f.zaraz._f(l);
            f.zaraz.init = () => {
                var m = g.getElementsByTagName(i)[0], n = g.createElement(i), o = g.getElementsByTagName("title")[0];
                o && (f[h].t = g.getElementsByTagName("title")[0].text);
                f[h].x = Math.random();
                f[h].w = f.screen.width;
                f[h].h = f.screen.height;
                f[h].j = f.innerHeight;
                f[h].e = f.innerWidth;
                f[h].l = f.location.href;
                f[h].r = g.referrer;
                f[h].k = f.screen.colorDepth;
                f[h].n = g.characterSet;
                f[h].o = (new Date).getTimezoneOffset();
                if (f.dataLayer) for (const s of Object.entries(Object.entries(dataLayer).reduce(((t, u) => ({...t[1], ...u[1]})), {}))) zaraz.set(s[0], s[1], {scope: "page"});
                f[h].q = [];
                for (; f.zaraz.q.length;) {
                    const v = f.zaraz.q.shift();
                    f[h].q.push(v)
                }
                n.defer = !0;
                for (const w of [localStorage, sessionStorage]) Object.keys(w || {}).filter((y => y.startsWith("_zaraz_"))).forEach((x => {
                    try {
                        f[h]["z_" + x.slice(7)] = JSON.parse(w.getItem(x))
                    } catch {
                        f[h]["z_" + x.slice(7)] = w.getItem(x)
                    }
                }));
                n.referrerPolicy = "origin";
                n.src = "/cdn-cgi/zaraz/s.js?z=" + btoa(encodeURIComponent(JSON.stringify(f[h])));
                m.parentNode.insertBefore(n, m)
            };
            ["complete", "interactive"].includes(g.readyState) ? zaraz.init() : f.addEventListener("DOMContentLoaded", zaraz.init)
        }(w, d, "zarazData", "script");
    })(window, document);</script>
</head>
<body>
<h1>Not Found</h1>
<p>The requested URL was not found on this server.</p>
<hr>
<address>Apache/2.4.41 (Ubuntu) Server at preview.colorlib.com Port 443</address>
<script defer src="https://static.cloudflareinsights.com/beacon.min.js/v52afc6f149f6479b8c77fa569edb01181681764108816"
        integrity="sha512-jGCTpDpBAYDGNYR5ztKt4BQPGef1P0giN6ZGVUi835kFF88FOmmn8jBQWNgrNd8g/Yu421NdgWhwQoaOPFflDw=="
        data-cf-beacon='{"rayId":"7e49ace16b6207a5","version":"2023.4.0","b":1,"token":"cd0b4b3a733644fc843ef0b185f98241","si":100}'
        crossorigin="anonymous"></script>
</body>
</html>